import { Product, Category } from "../types";

export const products: Product[] = [
  {
    id: 1,
    name: "Classic Cotton T-Shirt",
    price: 49,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
    category: "tops",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black", "Navy", "Gray"],
    description: "Premium cotton t-shirt with a relaxed fit. Perfect for everyday wear.",
    isNew: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 2,
    name: "Slim Fit Denim Jeans",
    price: 89,
    originalPrice: 120,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500",
    category: "bottoms",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Indigo", "Black", "Light Wash"],
    description: "Modern slim fit jeans with stretch comfort. A wardrobe essential.",
    isSale: true,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: 3,
    name: "Wool Blend Overcoat",
    price: 249,
    image: "https://images.unsplash.com/photo-1544923246-77308dd6c9e5?w=500",
    category: "outerwear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Camel", "Black", "Charcoal"],
    description: "Elegant wool blend overcoat with a timeless silhouette.",
    rating: 4.9,
    reviews: 56,
  },
  {
    id: 4,
    name: "Silk Evening Dress",
    price: 189,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500",
    category: "dresses",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Burgundy", "Navy", "Black"],
    description: "Luxurious silk dress perfect for special occasions.",
    isNew: true,
    rating: 4.7,
    reviews: 43,
  },
  {
    id: 5,
    name: "Cashmere Sweater",
    price: 159,
    originalPrice: 199,
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500",
    category: "tops",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Cream", "Gray", "Navy", "Burgundy"],
    description: "Ultra-soft cashmere sweater for ultimate comfort and style.",
    isSale: true,
    rating: 4.9,
    reviews: 78,
  },
  {
    id: 6,
    name: "Tailored Chinos",
    price: 79,
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500",
    category: "bottoms",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Khaki", "Navy", "Olive", "Stone"],
    description: "Versatile tailored chinos with a modern fit.",
    rating: 4.5,
    reviews: 112,
  },
  {
    id: 7,
    name: "Leather Biker Jacket",
    price: 299,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500",
    category: "outerwear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Brown"],
    description: "Classic leather biker jacket with premium detailing.",
    rating: 4.8,
    reviews: 67,
  },
  {
    id: 8,
    name: "Linen Summer Dress",
    price: 129,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b5e0e6d?w=500",
    category: "dresses",
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Beige", "Sage"],
    description: "Breathable linen dress perfect for warm weather.",
    isNew: true,
    rating: 4.6,
    reviews: 34,
  },
  {
    id: 9,
    name: "Oversized Hoodie",
    price: 69,
    image: "https://images.unsplash.com/photo-1556821840-3a163f029b85?w=500",
    category: "tops",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Gray", "Black", "Navy", "Burgundy"],
    description: "Cozy oversized hoodie made from organic cotton.",
    rating: 4.7,
    reviews: 156,
  },
  {
    id: 10,
    name: "Pleated Midi Skirt",
    price: 89,
    originalPrice: 110,
    image: "https://images.unsplash.com/photo-1583496661160-fb9881a4c1e1?w=500",
    category: "bottoms",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Navy", "Cream"],
    description: "Elegant pleated midi skirt for versatile styling.",
    isSale: true,
    rating: 4.4,
    reviews: 28,
  },
  {
    id: 11,
    name: "Quilted Puffer Jacket",
    price: 179,
    image: "https://images.unsplash.com/photo-1544022613-df631b488665?w=500",
    category: "outerwear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Olive"],
    description: "Warm quilted puffer jacket with sustainable filling.",
    rating: 4.8,
    reviews: 92,
  },
  {
    id: 12,
    name: "Floral Maxi Dress",
    price: 149,
    image: "https://images.unsplash.com/photo-1496743946609-d84c22a59c20?w=500",
    category: "dresses",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Floral Blue", "Floral Pink", "Floral Green"],
    description: "Beautiful floral maxi dress for elegant occasions.",
    isNew: true,
    rating: 4.7,
    reviews: 51,
  },
];

export const categories: Category[] = [
  {
    id: "tops",
    name: "Tops",
    image: "https://images.unsplash.com/photo-1489987707043-4ccedab66d07?w=400",
    count: 45,
  },
  {
    id: "bottoms",
    name: "Bottoms",
    image: "https://images.unsplash.com/photo-1541099643745-4244024d5aca?w=400",
    count: 32,
  },
  {
    id: "outerwear",
    name: "Outerwear",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400",
    count: 28,
  },
  {
    id: "dresses",
    name: "Dresses",
    image: "https://images.unsplash.com/photo-1515372039744-b8f02a1ae4b6?w=400",
    count: 24,
  },
];